### ISSUE TITLE
Add optional parameter to exclude internal classes and methods etc.

### ISSUE THREAD

**Issue by bjornen77** [loxsmoke/mddox#16]
It would be good to have an optional parameter to exclude internal classes and methods from the generated documentation. Or maybe this is already possible?

**Comment by loxsmoke** [comment]
There is a way to limit the documentation of certain classes by using the --ignore-attribute switch and adding an attribute to classes that should be excluded.

**Comment by bjornen77** [comment]
Ok, good to know that that option exist, it will work for me at the moment. However, I think that adding the option to exclude internal classes and methods etc, without having to add an attribute, would be a really good addition. For example, If you want some public documentation for a library. Thank you for creating this awesome tool!

**Comment by loxsmoke** [comment]
Closing this for now. Not adding a new type of filtering to keep the tool simple.
