### ISSUE TITLE
[Feature Request] Option for ignoring types without documentation

### ISSUE THREAD

**Issue by ModernRonin** [loxsmoke/mddox#17]
Hi,

thanks for a super cool tool!

One thing that would be helpful would be a command-line switch that tells mddox to ignore types that have no comments. 

Would that be hard to do?

Thanks,
MR

**Comment by loxsmoke** [comment]
Currently, the easiest solution is to add an attribute to the class and use --ignore-attribute option when generating the documentation. See if that helps.

**Comment by loxsmoke** [comment]
Closing this. There is a simple workaround that is not elegant. Adding multiple ignore options would make tool much more complicated.
