### ISSUE TITLE
[Feature Request] Support for examples

### ISSUE THREAD

**Issue by doomchild** [loxsmoke/mddox#20]
Is there any way to have the tool also write out examples (using the `<example>` tag)?

**Comment by loxsmoke** [comment]
Could you provide the example of what the source comment looks like?

**Comment by doomchild** [comment]
This is the documentation for the `<example>` tags.

https://docs.microsoft.com/en-us/dotnet/csharp/codedoc#example

**Comment by loxsmoke** [comment]
My question was not clear. 
All data is available in XML file but I do not know where to put example text in generated markdown.  I thought that after seeing your example tag usage I would have some idea

**Comment by doomchild** [comment]
Oh, I'm sorry.  Here's an example of what our code looks like:

```csharp
/// <summary>
/// Maps the underlying value of a <see cref="Maybe"/> in a <code>null</code>-safe way.
/// </summary>
/// <typeparam name="B">The return type of the <code>morphism</code>.</typeparam>
/// <param name="morphism">The morphism.</param>
/// <param name="maybe">The maybe.</param>
/// <example>
/// Func<int, int> Square = value => value * value;
/// Maybe.Just(4)
///   .FMap(Square);
/// // => Just(16)
/// 
/// Maybe.Nothing()
///   .FMap(Square);
/// // => Nothing()
/// 
/// Maybe.Just<List<string>>(new List<string> { null })
///   .FMap(list => list[0]);
/// // => Nothing()
/// </example>
/// <returns>The mapped <see cref="Maybe"/>.</returns>
public static IMaybe<W> FMap<V, W>(Func<V, W> morphism, IMaybe<V> maybe) => maybe.FMap(morphism);
```

**Comment by loxsmoke** [comment]
Just FYI `<code>` tag is missing in your example. 

Example is a big comment and it cannot lose formatting in markdown. Having examples in markdown tables could be challenging.

Examples are like summaries. They can be added for classes, structs, enums and methods.  Mddox writes summaries for types right after the type name title and namespace line. The example section for the type could be added at the end of the type documentation after properties and methods tables. This is doable.

Summary comments for methods and properties are shown in the tables but adding long examples to the same tables would make documentation unreadable. Clearly formatting should be different but solution is not obvious. Any suggestions?

**Comment by doomchild** [comment]
One thought would be to emulate what the normal MS docs do.  Examples are shown on a page specific to the type, field, or method being inspected.  That has the unfortunate knock-on effect of resulting in a _lot_ of files being generated (which might look daunting), but some amount of hierarchy could help alleviate that.

Another option (which is what I think you suggested at the end of your comment) would be to have the table like it is now, but put each field, method, etc, below the table with examples and remarks.

**Comment by loxsmoke** [comment]
Adding examples for types is easy. For methods it looks easy when using --method-details flag.
Do you intend to have examples for properties and fields as well?

**Comment by doomchild** [comment]
Right now, that's not a use case we have.

**Comment by loxsmoke** [comment]
Try mddox 0.7.2 version. 
I added methods' examples when writing markdown with --method-details flag.
