### ISSUE TITLE
Do not include non-public classes and members

### ISSUE THREAD

**Issue by ridercz** [loxsmoke/mddox#21]
Currently documentation is generated for constructs that are not part of public API (internal classes, private members), which can lead to much confusion. 

There is no switch to ignore non-public members. Although I would expect that non-public members would be hidden from docs by default and if needed, have to be explicitly enabled.

**Comment by loxsmoke** [comment]
Filtering of items could be improved. No plans for it yet but will keep in mind this feature request.
