### ISSUE TITLE
Non fuctional internal links

### ISSUE THREAD

**Issue by ridercz** [loxsmoke/mddox#22]
When mddox generates heading with method name, the heading will contain internal hyperlinks within file itself (and with `-s` argument it will link to MSDN for common system types), which is just fine.

However it seems that the same algorithm is used for generating the table of methods, which leads to links within links, which is obviously not valid Markdown.

**Comment by loxsmoke** [comment]
Could you paste the markdown output example?

**Comment by loxsmoke** [comment]
0.9.1 fixes the issue.
