### ISSUE TITLE
export <example>tags to MD

### ISSUE THREAD

**Issue by dkurok** [loxsmoke/mddox#24]
Can you also export the <example>-tags of the XML-documentation into the markdown-document?

**Comment by loxsmoke** [comment]
I am trying to understand the use case. 
What tags do you have in mind?

**Comment by dkurok** [comment]
soryy ,it left out the XML-Tag: I mean the example-tag (including code-tags) in the XML-documentation. I Would like to give the devlopers using one of our libs some examples/using scenarios in the documentation.

**Comment by loxsmoke** [comment]
mddox prints examples in the md file. 
Can you build a small example and point out what you are getting now and what is desired output?
