### ISSUE TITLE
Feature request: unescape angle brackets

### ISSUE THREAD

**Issue by enriquein** [loxsmoke/mddox#30]
Given that .Net uses angle brackets extensively in code (for type parameters, comparisons, etc), and given that we need to escape these brackets as `&lt;` and `&gt;`, it would be great if somewhere in the translation to markdown the tool could unescape these back to `<` and `>`.

Simple example:
```
/// <example>
/// <code>
/// if (i &lt; 33) 
/// </code>
/// </example>
```

Generates `if (i &lt; 33)` but ideally it should output `if (i < 33)` because Markdown doesn't seem to support rendering HTML entities. 

PS: Thank you for making such an awesome tool. Now my team can finally have nicely rendered docs for our internal libraries.

**Comment by loxsmoke** [comment]
Do not have enough time for this at the moment but would gladly review the pull request if you would create one.

**Comment by loxsmoke** [comment]
Try the new version 0.14.2. Let me know if something is still missing
