### ISSUE TITLE
Bug generating heading links when including method details and formatting for Bitbucket

### ISSUE THREAD

**Issue by enriquein** [loxsmoke/mddox#31]
Not a big deal, but thought I'd report this. When using the option to include method details in combination with outputting Markdown for Bitbucket, I noticed that some of the method links are off. 

For example, I have a method `SendMessage(message)` which outputs this Markdown in the table:

```
| [**SendMessage([SendMessageRequest](#markdown-header-sendmessagerequest-class) message)**](#markdown-header-sendmessagesendmessagerequestmarkdown-header-sendmessagerequest-class-message) | Task<[SendMessageResponse](#markdown-header-sendmessageresponse-class)> | Send a message. |
```
Inspecting the HTML from Bitbucket, the correct id for the `h3` tag for this method is `markdown-header-sendmessagesendmessagerequest-message`. It looks like the tool is adding part of the link for the parameter in the method link.

Interestingly enough, one of the 3 methods in the table has the correct id. I'm not sure exactly why, but I have a suspicion that it's related to the fact that the method only uses standard .Net types:

```
| [**SendSimpleMessage(string sendTo, string subject, string message, bool isHtml)**](#markdown-header-sendsimplemessagestring-sendto-string-subject-string-message-bool-ishtml) | Task<[SendMessageResponse](#markdown-header-sendmessageresponse-class)> | Send a message. |
```

**Comment by loxsmoke** [comment]
Try the new version 0.14.2. Let me know if something is still missing
