### ISSUE TITLE
Missing summary info in markdown

### ISSUE THREAD

**Issue by luisxkimo** [loxsmoke/mddox#7]
Hi,

I'm trying to create md documentation file, but I can't see my _summary_ comment info in the markdown file. Here is an example:

![image](https://user-images.githubusercontent.com/6990299/78390121-4f33a780-75e4-11ea-943f-c5712c3d19c3.png)

![image](https://user-images.githubusercontent.com/6990299/78390182-725e5700-75e4-11ea-9554-1c04ec4f8a4e.png)

- 0.5.1 version of the tool
- DLL generated by taken from _published_ folder generated by `dotnet publish -f netstandard2.1 -o published`

**Comment by loxsmoke** [comment]
Is this the only missing summary? 

Check if the compiler-generated XML file is next to the assembly you are documenting.

**Comment by luisxkimo** [comment]
Hi,

I could review, this is the only info that I miss.

Yes, I'm using a DLL that have in the same directory the XML document generated. Here is the content for this example:

```xml
 <member name="M:Loc.Infrastructure.Core.ActiveDirectory.UserPrincipalExtensions.ToActiveDirectoryUser(System.DirectoryServices.AccountManagement.UserPrincipal,System.Collections.Generic.IReadOnlyCollection{System.String})">
	<summary>
	Transforms a <see cref="T:System.DirectoryServices.AccountManagement.UserPrincipal"/> into an <see cref="T:Loc.Infrastructure.Core.ActiveDirectory.Model.ActiveDirectoryUser"/> object;
	</summary>
	<param name="principal">The principal to be transformed.</param>
	<param name="relevantProperties">Additional properties to be included.</param>
	<returns>A new instance of <see cref="T:Loc.Infrastructure.Core.ActiveDirectory.Model.ActiveDirectoryUser"/> with the relevant properties of the principal.</returns>
</member>
```

**Comment by loxsmoke** [comment]
Could you paste the full signature of the class and the method?

**Comment by luisxkimo** [comment]
Sure. Here is the signature:
```csharp
        /// <summary>
        /// Transforms a <see cref="UserPrincipal"/> into an <see cref="ActiveDirectoryUser"/> object;
        /// </summary>
        /// <param name="principal">The principal to be transformed.</param>
        /// <param name="relevantProperties">Additional properties to be included.</param>
        /// <returns>A new instance of <see cref="ActiveDirectoryUser"/> with the relevant properties of the principal.</returns>
        public static ActiveDirectoryUser ToActiveDirectoryUser(this UserPrincipal principal, IReadOnlyCollection<string> relevantProperties)
        {
           //code
        }
```

**Comment by loxsmoke** [comment]
Could not reproduce the problem. Must be something environment-related.

**Comment by luisxkimo** [comment]
Well, we will try to test in other environments, and let you know if we find some details about our problem.

Regards
